### ISSUE TITLE
Minor typo in leveling up: "You're now a danger Level 4!"

### ISSUE THREAD

**Issue by katubug** [Nierhain/DangerLiesAhead#11]
I'm assuming this is intended to be "**at** danger Level 4"? Also, I'm not sure if it would be difficult to enact, but I'd love a config option to be able to change what that text says, so I can tailor it to my modpack's theme a bit more. A different sound option would be nice, too, but that's a very minor thing.

Thanks for the cool mod :D

**Comment by Nierhain** [comment]
It's intended the way it is, but I should have phrased it "a level X danger/threat" or something like that.
You can change the sound with a resource pack (though also the text but I'll add a config option for that as it's easier to change).

**Comment by katubug** [comment]
Ah, good point about the resource pack! Also thank you, and holy crap that was fast! <3
