### ISSUE TITLE
Crash dealing with a type of entity from Mobultion

### ISSUE THREAD

**Issue by ChromaPIE** [Nierhain/DangerLiesAhead#12]
Not sure if this mod is still under any kind of maintainance.

Here's the crash report:https://paste.ubuntu.com/p/xRSFr8MQZs/

The game crashes probably when DLA starts trial to deal with a type of entity from the mod Mobultion called Skeleton Remains.

**Comment by Nierhain** [comment]
I'm still maintaining and developing this mod, don't worry.
Right now, I'm looking into some other bug fixes or rather implementations that are more severe, as Mobultion seems to be one of the only mods having this sort of problem. I could be wrong though.
Either way, thanks for the submission, I'll definitely look into it
